frontend/Dockerfile
frontend/frontend/private.py
frontend/frontend/public.py
frontend/templates/query_page.html
tests/data/exp.yaml
tests/test_basic.py

* having each experiment be a specific number of responses, `max_responses`. This key can be specified in the YAML file (see `tests/data/exp.yaml` for an example).
* Showing the participant ID only at the end

MAINT: implement max_responses (and showing participant ID then)

---

frontend/templates/query_page.html

BUG: only allow max_iter at most on query page

---

frontend/Dockerfile
frontend/frontend/__init__.py
frontend/frontend/manager.py
frontend/frontend/plotting.py
frontend/frontend/private.py
frontend/requirements.txt
frontend/templates/dashboard.html
tests/test_basic.py

Implements dashboard graphs in Bokeh instead of Matplotlib. This allows for interactivity and reduces the amount of code required.

MAINT: Bokeh dashboard graphs

---

.gitignore
backend/backend/algs/utils.py
backend/backend/core.py
docker-compose.yml
frontend/Dockerfile
frontend/frontend/__init__.py
frontend/frontend/private.py
frontend/frontend/public.py
frontend/templates/dashboard.html
tests/test_basic.py
tests/utils.py

It allow for the download of experiments, and allows restoring server state from this file.
This has the added benefit of preserving state through reboot.
This PR closes #16.

ENH: allow downloading/restoring experiments

---

launch.sh
salmon/utils.py

Makes some AWS fixes for deployment. It resolves two issues:
* Backend workers were dying repeatedly.
* Logs weren't being piped to stdout with Gunicorn.

MAINT: AWS fixes for deployment

---

salmon/frontend/plotting.py
salmon/frontend/private.py
salmon/frontend/public.py
salmon/utils.py
templates/dashboard.html

This PR implements does the following:
1. Improves dashboard stability. Now, the dashboard will be available even when plotting errs out.
2. Improves the API documentation, and better links to it.
3. Allows server to reload on file change while debugging.
The motivation is (1), which happened during another deploy experiment.

MAINT: dashboard stability, document API, allow server to restart on file changes

---

docs/source/api.rst
docs/source/developers.rst
docs/source/index.rst

Documents implementing new algorithms.

DOC: document implementing new algorithms

---

.travis.yml
salmon/frontend/plotting.py
salmon/frontend/private.py
salmon/frontend/static/targets/names.csv
salmon/frontend/utils.py
salmon/triplets/algs/adaptive/search/tests/test_search_refactor.py
templates/dashboard.html
tests/data/active.yaml

It shows the embedding on the dashboard. Here's a basic example with text targets:

ENH: show embeddings on dashboard

---

templates/query_page.html

This implements some client side tracking of the queries seen so far. Currently, it's the last 5 queries. If the current query is any of these N queries, a new query will be requested.
This closes #60. This PR is not user-configurable, but I'm not super worried about that: anyone can implement their own query page.

MAINT: make sure the user doesn't see repeat queries

---

salmon/triplets/algs/_adaptive_runners.py
salmon/triplets/algs/adaptive/__init__.py
salmon/triplets/algs/adaptive/_score.py
salmon/triplets/algs/adaptive/search/tests/test_uncertainty.py
tests/data/active.yaml

This PR implements uncertainty sampling.
This closes #63.

ENH: Implements uncertainty sampling

---

docs/source/_static/strangefruit.html
docs/source/conf.py

MAINT: doc link

---

docs/source/installation.rst
salmon.yml
salmon/frontend/plotting.py
salmon/frontend/private.py
salmon/triplets/algs/_random_sampling.py
salmon/triplets/algs/_round_robin.py
setup.py

Small deployment fixes after running adaptive algorithms on EC2, specifically:
* Adding recommended instance types (ran into issues with too few CPU cores for adaptive algs)
* Reducing computation required for random/round robin sampling.

MAINT: adaptive deployment fixes

---

.travis.yml
docs/source/algorithms.rst
docs/source/getting-started.rst
examples/alien-eggs/init.yaml
examples/colors/colors.yaml
examples/num-users/sim.py
launch.sh
salmon/_junk.py
salmon/backend/core.py
salmon/frontend/private.py
salmon/frontend/public.py
salmon/triplets/algs/_test_runner.py
salmon/triplets/algs/adaptive/_embed.py
salmon/triplets/manager.py
salmon/utils.py
templates/dashboard.html
templates/query_page.html
tests/data/active.yaml
tests/data/exp-active-bad.yaml
tests/test_active.py
tests/test_backend.py

It irons out some of the bumps from the adaptive road test. Specifically, it does the following:
It also does some smaller maintenance changes:
This PR addresses #83, closes #84 and addresses https://github.com/stsievert/salmon/issues/82#issuecomment-716768050.
[z]:https://redis.io/commands/zpopmax
[bz]:https://redis.io/commands/bzpopmax

Adaptive road test fixes

---

.gitignore
Makefile
docker-compose.yml
docs/source/getting-started.rst
docs/source/installation.rst
salmon/frontend/private.py
salmon/frontend/utils.py
tests/test_backend.py
tests/test_basic.py
tests/test_examples.py
tests/utils.py

It allows users to create usernames/passwords so I don't have to provide it.
This PR closes #105

ENH: allow user to provide authorization creds

---

.gitignore
salmon/backend/alg.py
salmon/frontend/private.py
salmon/triplets/algs/_adaptive_runners.py
salmon/triplets/algs/_random_sampling.py
salmon/triplets/algs/_round_robin.py
tests/test_basic.py
tests/test_examples.py
tests/utils.py

Some maintenance work around passwords/resetting.
This PR closes #82

MAINT: better reset and passwords

---

.github/workflows/docs.yml
salmon/frontend/private.py

* Changes HTML title to include the correct version
* Makes sure only 1st/last letters are displayed
* Only pushes documentation changes on releases.

MAINT: clean before release

---

docs/source/algorithms.rst
salmon/triplets/offline.py
salmon/triplets/samplers/__init__.py
salmon/triplets/samplers/_validation.py
salmon/triplets/samplers/adaptive/_embed.py
salmon/triplets/samplers/adaptive/_noise_models.py
tests/test_active.py
tests/test_basic.py
tests/utils.py

It implements validation sampling.
This PR closes #111.

ENH: implement validation sampling

---

templates/query_page.html

Allows styles to be applied to the target text header
None

added id tag to the div containing the header for the target

---

.github/workflows/test.yml
.github/workflows/test_pip.yml
ami/host.sh
ami/salmon.service
ami/salmon.sh
docs/source/installation.rst
salmon.yml
tests/test_examples.py

It updates the documentation for EC2 installation (mostly around the AMI ID).

MAINT: Amazon EC2 installation updates

---

.github/workflows/docs.yml
.github/workflows/test.yml
README.md
tests/test_offline.py
tests/utils.py

Build docs faster

---

.github/workflows/docs.yml
docs/source/faq.rst
docs/source/index.rst

Add citation
